name: lesson_localization
description: Flutter Localization App

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/languages/
    - assets/animals/bird/
    - assets/animals/cat/
    - assets/animals/chameleon/
    - assets/animals/cow/
    - assets/animals/dog/
    - assets/animals/monkey/
    - assets/animals/penguin/
    - assets/animals/pig/
    - assets/animals/rat/
    - assets/animals/snake/
    - assets/animals/squirrel/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700